#!/bin/bash

sudo apt-get update # update the raspi
sudo apt-get upgrade

sudo apt-get install tesseract-ocr #install OCR Engine
sudo apt-get install festival #install text to speech converter

sudo apt-get install build-essential cmake pkg-config  #install dependencies for opencv
sudo apt-get install libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
sudo apt-get install libxvidcore-dev libx264-dev
sudo apt-get install libgtk2.0-dev libgtk-3-dev
sudo apt-get install libatlas-base-dev gfortran
sudo apt-get install python2.7-dev python3-dev

cd ~    #get opencv
wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.4.1.zip
unzip opencv.zip

wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/3.4.1.zip # get opencv extras
unzip opencv_contrib.zip

wget https://bootstrap.pypa.io/get-pip.py  #get pip
sudo python get-pip.py
sudo python3 get-pip.py

sudo pip install virtualenv virtualenvwrapper # get virtualenv
sudo rm -rf ~/.cache/pip

echo -e "\n# virtualenv and virtualenvwrapper" >> ~/.profile # add to profile
echo "export WORKON_HOME=$HOME/.virtualenvs" >> ~/.profile
echo "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3" >> ~/.profile
echo "source /usr/local/bin/virtualenvwrapper.sh/" >> ~/.profile

source ~/.profile
mkvirtualenv cv -p python3 # create the opencv virtual env for project

workon cv

pip install numpy

cd ~/opencv-3.4.1/    # make opencv in build
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.4.1/modules \
      -D BUILD_EXAMPLES=ON ..

find /etc/dphys-swapfile -type f -exec -i 's/CONF_SWAPSIZE=100/CONF_SWAPSIZE=1024/g' {} \;   # temporarily increase the swap memory size to allow opencv to compile without memory problems
sudo /etc/init.d/dphys-swapfile stop
sudo /etc/init.d/dphys-swapfile start

make -j4 # compile opencv
sudo make install
sudo ldconfig

cd /usr/local/lib/python3.5/site-packages/       # check if filename is correct
builtfile=$( find . -regex '.*cv2.\+\.so' | basename )
if [ builtfile != "" ]    # if builtfile string is empty, there are no misnamed
then                      # files in the directory
  sudo mv "$builtfile" "cv2.so"
fi

ln -s /usr/local/lib/python3.5/site-packages/cv2.so cv2.so

echo "done"
